name: QA CI Android Pipeline

on:
  workflow_call:
    inputs:
      provider:
        description: 'Provider Name'
        required: true
        type: string
      environment:
        description: 'Deployment Environment'
        required: true
        type: string

jobs:
  print-inputs:
    runs-on: ubuntu-latest
    steps:
      - name: Print Inputs
        run: |
          echo "Android Pipeline Triggered for Provider ${{ github.event.inputs.provider }}"
          echo "Environment ${{ github.event.inputs.environment }}"

  build-android:
    runs-on: [ self-hosted, macOS, X64 ]
    defaults:
      run:
        working-directory: ./dawy

    strategy:
      matrix:
        build-type: [ debug, release ]

    steps:
    - name: Check PWD
      run: pwd

    - name: Checkout
      uses: actions/checkout@v4.1.4
      with:
        ref: ${{ github.ref }}

    - name: Set up Node.js environment
      uses: actions/setup-node@v4.0.2
      with:
        cache: "yarn"
        cache-dependency-path: ./dawy/yarn.lock

    - name: Install Node modules
      run: yarn

    - name: Cache Gradle Wrapper
      uses: actions/cache@v4.0.2
      with:
        path: ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-wrapper-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}

    - name: Cache Gradle Dependencies
      uses: actions/cache@v4.0.2
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-caches-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-caches-

    - name: Make Gradlew Executable
      run: chmod +x android/gradlew

    - name: Generate ${{ matrix.build-type }} APK
      run: |
        cd android
        ./gradlew assemble${{ matrix.build-type }}

    - name: Generate ${{ matrix.build-type }} Bundle
      run: |
        cd android
        ./gradlew bundle${{ matrix.build-type }}

    # Upload to Artifact
    - name: Upload ${{ matrix.build-type }} APK and Bundle as artifacts
      uses: actions/upload-artifact@v4
      with:
        name: android-${{ matrix.build-type }}-files
        path: |
          dawy/android/app/build/outputs/apk/${{ matrix.build-type }}/app-${{ matrix.build-type }}.apk
          dawy/android/app/build/outputs/bundle/${{ matrix.build-type }}/app-${{ matrix.build-type }}.aab
