name: Run main pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      provider_MoveMatic:
        description: "MoveMatic"
        required: false
        type: boolean

jobs:
  # Dummy job with no dependencies required
  check-pwd:
    runs-on: [ self-hosted, macOS, X64 ]
    steps:
      - name: Check PWD
        run: echo running from $PWD

  # print-secret:
  #   runs-on: [ self-hosted, macOS, X64 ]
  #   steps:
  #     - name: Print GitHub Secret
  #       run: |
  #         echo '${{ toJson(secrets) }}' | jq 'keys' | sed 's/./& /g'
  #         echo ${{secrets.PROVIDER_NAME}} | sed 's/./& /g'

  print-vars:
    runs-on: [ self-hosted, macOS, X64 ]
    steps:
      - name: Print GitHub Variables
        run: echo ${{vars}}

  # # Select providers dynamically based on workflow inputs
  # filter-providers:
  #   needs: check-pwd
  #   runs-on: ubuntu-latest
  #   outputs:
  #     selected_providers: ${{ steps.set-output.outputs.selected_providers }}
  #   steps:
  #     - name: Generate Selected Providers
  #       id: set-output
  #       run: |
  #         selected=()
  #         if [ "${{ inputs.provider_dawy }}" == "true" ]; then
  #           selected+=("Dawy")
  #         fi
  #         if [ "${{ inputs.provider_delta }}" == "true" ]; then
  #           selected+=("Delta")
  #         fi
  #         if [ "${{ inputs.provider_al_ahmadi }}" == "true" ]; then
  #           selected+=("Al-Ahmadi")
  #         fi
  #         echo "Selected providers: ${selected[@]}"
  #         echo "::set-output name=selected_providers::$(echo ${selected[@]} | jq -R -s -c 'split(" ")')"

  # # Trigger child workflows for each selected provider
  # trigger-providers-workflows:
  #   needs: filter-providers
  #   runs-on: self-hosted
  #   strategy:
  #     matrix:
  #       provider: ${{ fromJson(needs.filter-providers.outputs.selected_providers) }}
  #   steps:
  #     - name: Checkout repository
  #       uses: actions/checkout@v4

  #     - name: Trigger Child Workflow for ${{ matrix.provider }}
  #       run: |
  #         echo "Triggering workflow for provider ${{ matrix.provider }}"

  #     - name: Authenticate GitHub CLI
  #       run: |
  #         echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token

  #     # - name: Trigger Child Workflow
  #     #   run: |
  #     #     gh workflow run qa-ci-pipeline.yaml --ref ${{ github.ref_name }} -f environment=QA -f provider=${{ matrix.provider }}

  # # Build iOS using self-hosted runner
  # build-ios-self:
  #   needs: filter-providers
  #   uses: ./.github/workflows/build-ios-self.yml
  #   with: 
  #       provider: ${{ needs.filter-providers.outputs.selected_providers }}
  #       environment: QA
  #   secrets: inherit

  # # Build Android using self-hosted runner
  # build-android-self:
  #   needs: filter-providers
  #   uses: ./.github/workflows/build-android-self.yml
  #   with: 
  #       provider: ${{ needs.filter-providers.outputs.selected_providers }}
  #       environment: QA
  #   secrets: inherit
